#!/usr/bin/env python3
from pathlib import Path
import json

root = Path(__file__).resolve().parents[1]
out = root / "Docs/Localization/Generated"
out.mkdir(parents=True, exist_ok=True)
localizable = json.loads((root / "Narabi/Localizable.xcstrings").read_text(encoding="utf-8"))["strings"]
info = json.loads((root / "Narabi/InfoPlist.xcstrings").read_text(encoding="utf-8"))["strings"]
locales = sorted({locale for entry in localizable.values() for locale in entry.get("localizations", {})})

def value(entry, locale):
    return entry.get("localizations", {}).get(locale, {}).get("stringUnit", {}).get("value", "")

for locale in locales:
    lines = [
        f"# {locale}", "",
        "> Generated from the Xcode string catalogs. Do not edit this file directly.",
        "> Xcode文字列カタログから生成されています。このファイルを直接編集しないでください。", "",
        "## App and permission text", "",
    ]
    for key in sorted(info):
        lines += [f"### `{key}`", "", f"- English: {value(info[key], 'en')}", f"- Current: {value(info[key], locale)}", ""]
    lines += ["## Interface text", ""]
    for key in sorted(localizable):
        en = value(localizable[key], "en")
        current = value(localizable[key], locale)
        lines += [f"### `{key}`", "", f"- English: {en}", f"- Current: {current}", ""]
    (out / f"{locale}.md").write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

names = [
    "# Localized App Names / 各言語のアプリ名", "",
    "These are the official names for the initial release, generated from `Narabi/InfoPlist.xcstrings`. Reviews and future improvements remain welcome through a Translation issue or a focused pull request.", "",
    "The Japanese name is `並び替えでポン`. Preserve the idea of arranging pages easily and finishing quickly; a literal translation is not required.", "",
]
for locale in locales:
    names += [f"## `{locale}`", "", f"- Current name: `{value(info['CFBundleDisplayName'], locale)}`", ""]
(root / "Docs/Localization/APP_NAMES.md").write_text("\n".join(names).rstrip() + "\n", encoding="utf-8")
print(f"Generated {len(locales)} locale review files")
